import Document, { Html, Head, Main, NextScript } from 'next/document'
// import  logo from '../../public/Image/logo_blanco_favicon.png'
class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <body className="my-body-class">
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
